# Generated by Django 2.1.7 on 2019-08-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0026_auto_20190325_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('domain_name', models.CharField(blank=True, max_length=64, verbose_name='Domain Name')),
                ('git_address', models.CharField(blank=True, max_length=128, verbose_name='Git Address')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Open port')),
                ('type', models.CharField(blank=True, choices=[('Java', 'java'), ('React', 'react'), ('Cpp', 'c++'), ('Python', 'python'), ('Middleware', 'Middleware'), ('Other', 'Other')], default='Java', max_length=16, null=True, verbose_name='Project type')),
                ('created_by', models.CharField(blank=True, max_length=32, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('dev_users', models.ManyToManyField(blank=True, related_name='users1', to=settings.AUTH_USER_MODEL, verbose_name='Dev Users')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.Project')),
                ('sa_users', models.ManyToManyField(blank=True, related_name='users2', to=settings.AUTH_USER_MODEL, verbose_name='Sa Users')),
                ('scrum_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Scrum Master')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
